/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type?: "article" | "video" | "download" | "link";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: "book" | "code" | "lightbulb" | "rocket" | "target" | "check";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  isFreePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  isPopular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage{..., alt},    level,    price,    "isPopular": coalesce(isPopular, false),    "studentCount": coalesce(studentCount, 0),    learningOutcomes[]{_key, icon, title, description},    instructor->{      _id,      name,      "slug": slug.current,      photo{..., alt},      expertise,      bio    },    category->{      _id,      title,      "slug": slug.current,      description    }  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  isPopular: boolean | false;
  studentCount: number | 0;
  learningOutcomes: Array<{
    _key: string;
    icon: "book" | "check" | "code" | "lightbulb" | "rocket" | "target" | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    expertise: string | null;
    bio: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug] {    _id,    title,    "slug": slug.current,    summary,    coverImage{..., alt},    level,    price,    "isPopular": coalesce(isPopular, false),    "studentCount": coalesce(studentCount, 0),    learningOutcomes[]{_key, icon, title, description},    instructor->{      _id,      name,      "slug": slug.current,      photo{..., alt},      expertise,      bio    },    category->{      _id,      title,      "slug": slug.current,      description    },    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        videoUrl,        poster{..., alt},        duration,        "isFreePreview": coalesce(isFreePreview, false),        "studentCount": coalesce(studentCount, 0)      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  isPopular: boolean | false;
  studentCount: number | 0;
  learningOutcomes: Array<{
    _key: string;
    icon: "book" | "check" | "code" | "lightbulb" | "rocket" | "target" | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    expertise: string | null;
    bio: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      videoUrl: string | null;
      poster: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        _type: "image";
      } | null;
      duration: number | null;
      isFreePreview: boolean | false;
      studentCount: number | 0;
    }> | null;
  }> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug] {    _id,    title,    "slug": slug.current,    videoUrl,    poster{..., alt},    duration,    "isFreePreview": coalesce(isFreePreview, false),    "studentCount": coalesce(studentCount, 0),    notes,    keyPoints,    proTip,    resources[]{_key, type, title, description, url}  }
export type LESSON_BY_SLUG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  duration: number | null;
  isFreePreview: boolean | false;
  studentCount: number | 0;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "download" | "link" | "video" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_CONTEXTS_FOR_LESSON_QUERY
// Query: *[_type == "course" && references($lessonId)] | order(title asc) {    _id,    title,    "slug": slug.current,    instructor->{      _id,      name,      "slug": slug.current,      photo{..., alt},      expertise,      bio    },    category->{      _id,      title,      "slug": slug.current,      description    },    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        videoUrl,        poster{..., alt},        duration,        "isFreePreview": coalesce(isFreePreview, false),        "studentCount": coalesce(studentCount, 0)      }    }  }
export type COURSE_CONTEXTS_FOR_LESSON_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    expertise: string | null;
    bio: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      videoUrl: string | null;
      poster: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        _type: "image";
      } | null;
      duration: number | null;
      isFreePreview: boolean | false;
      studentCount: number | 0;
    }> | null;
  }> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    photo{..., alt},    expertise,    bio  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  expertise: string | null;
  bio: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug] {    _id,    name,    "slug": slug.current,    photo{..., alt},    expertise,    bio,    "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      coverImage{..., alt},      level,      price,      "isPopular": coalesce(isPopular, false),      "studentCount": coalesce(studentCount, 0),      category->{_id, title, "slug": slug.current, description}    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  expertise: string | null;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    isPopular: boolean | false;
    studentCount: number | 0;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
      description: string | null;
    } | null;
  }>;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug] {    _id,    title,    "slug": slug.current,    description,    "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      coverImage{..., alt},      level,      price,      "isPopular": coalesce(isPopular, false),      "studentCount": coalesce(studentCount, 0),      instructor->{_id, name, "slug": slug.current, photo{..., alt}, expertise, bio}    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    isPopular: boolean | false;
    studentCount: number | 0;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        _type: "image";
      } | null;
      expertise: string | null;
      bio: string | null;
    } | null;
  }>;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(slug.current asc) {    "slug": slug.current  }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] | order(slug.current asc) {    "slug": slug.current  }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage{..., alt},\n    level,\n    price,\n    "isPopular": coalesce(isPopular, false),\n    "studentCount": coalesce(studentCount, 0),\n    learningOutcomes[]{_key, icon, title, description},\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo{..., alt},\n      expertise,\n      bio\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current,\n      description\n    }\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage{..., alt},\n    level,\n    price,\n    "isPopular": coalesce(isPopular, false),\n    "studentCount": coalesce(studentCount, 0),\n    learningOutcomes[]{_key, icon, title, description},\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo{..., alt},\n      expertise,\n      bio\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current,\n      description\n    },\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        videoUrl,\n        poster{..., alt},\n        duration,\n        "isFreePreview": coalesce(isFreePreview, false),\n        "studentCount": coalesce(studentCount, 0)\n      }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    poster{..., alt},\n    duration,\n    "isFreePreview": coalesce(isFreePreview, false),\n    "studentCount": coalesce(studentCount, 0),\n    notes,\n    keyPoints,\n    proTip,\n    resources[]{_key, type, title, description, url}\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && references($lessonId)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo{..., alt},\n      expertise,\n      bio\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current,\n      description\n    },\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        videoUrl,\n        poster{..., alt},\n        duration,\n        "isFreePreview": coalesce(isFreePreview, false),\n        "studentCount": coalesce(studentCount, 0)\n      }\n    }\n  }\n': COURSE_CONTEXTS_FOR_LESSON_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    photo{..., alt},\n    expertise,\n    bio\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug] {\n    _id,\n    name,\n    "slug": slug.current,\n    photo{..., alt},\n    expertise,\n    bio,\n    "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      coverImage{..., alt},\n      level,\n      price,\n      "isPopular": coalesce(isPopular, false),\n      "studentCount": coalesce(studentCount, 0),\n      category->{_id, title, "slug": slug.current, description}\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      coverImage{..., alt},\n      level,\n      price,\n      "isPopular": coalesce(isPopular, false),\n      "studentCount": coalesce(studentCount, 0),\n      instructor->{_id, name, "slug": slug.current, photo{..., alt}, expertise, bio}\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] | order(slug.current asc) {\n    "slug": slug.current\n  }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)] | order(slug.current asc) {\n    "slug": slug.current\n  }\n': LESSON_SLUGS_QUERY_RESULT;
  }
}
